M48
; DRILL file {KiCad 8.0.8} date 2025-01-23T19:06:38+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-23T19:06:38+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1024
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1575
%
G90
G05
T1
X3.376Y-2.7795
X3.376Y-3.8819
X4.25Y-3.3602
T2
X2.9646Y-4.4882
X5.6496Y-1.0433
T3
X5.1575Y-3.5039
M30
